# Generated by Django 4.0.4 on 2022-05-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_citizen_hadcovid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='dateOfBirth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='previousConditions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
