# Generated by Django 4.0.4 on 2022-05-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_citizen_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='previousConditions',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='zipCode',
            field=models.IntegerField(),
        ),
    ]
