# Generated by Django 4.0.4 on 2022-06-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_citizen_previousconditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='zipCode',
            field=models.IntegerField(null=True),
        ),
    ]
