# Generated by Django 4.0.4 on 2022-06-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_citizen_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='zipCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
