# Generated by Django 4.0.4 on 2022-06-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_citizen_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='otherConditions',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
